name: Assets Update

on:
  workflow_dispatch:
  schedule:
    - cron: "50 0 * * *" # run every day at 00:50
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch version file from gh-pages
        run: |
          mkdir -p .data
          if curl -L -s -f -o .data/version.json https://league-fan.github.io/cdragon/version.json; then
            echo "Successfully fetched version.json from GitHub Pages"
            cat .data/version.json
          fi

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x # Run with latest stable Deno.

      - name: Update Assets
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" || "${{ github.event_name }}" == "push" ]]; then
            deno run crawler --force
          else
            deno run crawler
          fi

      - name: Check if Crawling is done
        id: check_crawling
        run: |
          if [ -f .data/index.html ]; then
            echo "Crawling is done"
            echo "CRAWLING_DONE=true" >> "${GITHUB_OUTPUT}"
          else
            echo "Crawling is not done"
            echo "CRAWLING_DONE=false" >> "${GITHUB_OUTPUT}"
          fi

      - name: Prepare Message
        id: prepare_message
        if: ${{ steps.check_crawling.outputs.CRAWLING_DONE == 'true' }}
        run: |
          echo "DEPLOY_VERSION=`cat .data/version.json | jq -r '.version'`" >> "${GITHUB_OUTPUT}"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ steps.check_crawling.outputs.CRAWLING_DONE == 'true' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .data
          commit_message: "${{ github.event.head_commit.message }} ${{ steps.prepare_message.outputs.DEPLOY_VERSION }}"
