name: Assets Update

on:
  workflow_dispatch:
  schedule:
    - cron: "50 0 * * *" # run every day at 00:50
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x # Run with latest stable Deno.

      - name: Update Assets
        id: update-assets
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            deno run crawler --force
          else
            deno run crawler
          fi
          deno run genIndex

      - name: Prepare tag
        id: prepare_tag
        if: ${{ !contains(steps.update-assets.outputs.stdout, 'no need to crawl') }}
        run: |
          echo "DEPLOY_TAG=`cat .data/version.json | jq -r '.version'`" >> $GITHUB_ENV
          echo "DEPLOY_TIME=`cat .data/version.json | jq -r '.crawledAt'`" >> $GITHUB_ENV

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ !contains(steps.update-assets.outputs.stdout, 'no need to crawl') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .data
          tag_name: ${{ steps.prepare_tag.outputs.DEPLOY_TAG }}
          tag_message: 'Deployment of ${{ steps.prepare_tag.outputs.DEPLOY_TAG }} at ${{ steps.prepare_tag.outputs.DEPLOY_TIME }}'
