name: Assets Update

on:
  workflow_dispatch:
  schedule:
    - cron: "50 0 * * *" # run every day at 00:50
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x # Run with latest stable Deno.

      - name: Update Assets
        id: update-assets
        run: deno run crawler

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ !contains(steps.update-assets.outputs.stdout, 'no need to crawl') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .data
